---
# DGX Server Configuration

# cachefilesd
cachefilesd_cache_dir: /raid
cachefilesd_cache_tag: dgx1cache

# Collectd
collectd_python_modules:
  - dcgm_collectd
with_dcgm_collectd: true

# Docker Configuration
# Setting reference: https://docs.nvidia.com/deeplearning/dgx/user-guide/index.html
docker_daemon_json:
  bip: 192.168.99.1/24
  default-shm-size: 1G
  default-ulimits:
    memlock:
      name: memlock
      hard: -1
      soft: -1
    stack:
      name: stack
      hard: 67108864
      soft: 67108864
  default-runtime: nvidia
  runtimes:
    nvidia:
      path: /usr/bin/nvidia-container-runtime
      runtimeArgs: []
